---
title: "Final Grade Reflection"
author: "Scott Brydon"
format: pdf
editor: visual
---

I believe I've earned an A in this course because I've demonstrated adequate fulfillment of the five course objectives. First and foremost, I believe I was able to demonstrate proficiency in all of the learning targets established in the class. The following list contains what supporting artifacts correspond to my mastery of each learning target:

1.  WD-1 Importing Data - (Challenge 3 Loading California and Avocado Data, Preview Activity 2 Step 2)
2.  WD-2 Selecting Necessary Columns - (Challenge 3 Letter B)
3.  WD-3 Filtering Rows - (Lab 3 Study Subjects, Practice Activity 5 Question 1, Lab 3 Familiar Words)
4.  WD-4 Modifying and Creating Variables - (Lab 3 Question 4/6, Lab 4 Question 6, Practice Activity 5 Adjusting Time Zone)
5.  WD-5 Mutating Joins - (Preview Activity 4 A/B)
6.  WD-6 Filtering Joins - (Lab 4 Question 7)
7.  WD-7 Pivoting Data Frames - (Lab 4 Question 6/7)
8.  R-1 Professional Looking Analysis - (Lab 3)
9.  R-2 Well Documented and Tidy Code - (Lab 3 Familiar Words, Lab 4 Question 5)
10. R-3 Resistant to Changes - (Lab 7 Part 2 Task1/2/3, Lab 4 Question 4, Challenge 3 Letter B)
11. DVS-1 Visualizations for a Variety of Data Types - (Lab 4 Question 7, Lab 5 Time Series Plots #2, Lab 7 Task 4, Challenge 7 Part 3)
12. DVS-2 Plot Modifications for Clear Visuals - (Lab 4 Question 7, Challenge 7 Part 3)
13. DVS-3 Creative Visuals - (Lab 5 Time Series Plots Question 2, Challenge 7 Part 3, Challenge 4 Letter C)
14. DVS-4 Calculating Numerical Summaries - (Lab 3 Familiar Words)
15. DVS-5 Summaries of Variables Across Groups - (Challenge 3 Letter B)
16. DVS-6 Tables with Clear Summaries - (Challenge 9 Part 2 Question 1 and 2, Lab 4 Exercises 3/4)
17. DVS-7 Creativity in Tables - (Challenge 9 Part 2 Question 1 and 2)
18. PE-1 Concise Code - (Lab 4 Reshaping Question 6, Challenge 3 Letter B, Lab 5 Time Series Plots #2)
19. PE-2 Functions to Reduce Repetition - (Lab 8 Phrase Function/Sing Day Function)
20. PE-3 Iteration to Reduce Repetition - (Lab 8 Step Four)
21. PE-4 Modern Tools - (Lab 7 Task 5/6, Lab 8 Step Four, Lab 4 Exercise Question 4)
22. DSM-1 Simulating Data for Probability Models - (Practice Activity 9 Instruments: Catching a Con)
23. DSM-2 Regression / Summary Measures - (Lab 9 Modelling the Number of Allison's Question 4 and 5)

The majority of my challenges and labs assigned throughout this quarter were submitted on time and were always full attempts. Most of these assignments needed to be revised to answer the questions correctly and to adhere to the proper format and tidiness asked of us in class. I completed all the revisions that were asked of me, and showed improvement in my code as a result of these revisions. For example, I had to revise my solution for Lab 2 twice because I didn't understand how to properly show and explain the contents of a data set to educate the viewer. After those revisions, I was able to adequately explain the contents and survey methods of the hip hop data set in Lab 3. In Lab 7, I had issues choosing the correct plots for the visualization of the NAs and re-scaled fish length in the data, understanding the argument structure of the stopifnot function, and eliminating redundancy in my functions. After completing the revisions, I showed a better understanding of the correct visualizations for different data types in Lab 9 when visualizing summary measures of the total number of babies in the US named Allison per year. I attempted every challenge that was given throughout the quarter, and showed adequate evidence of extended learning by completing all of those challenges. In Challenge 2, I completed the spiciest challenge option, where I learned how to change the positions of annotations on graphs. In Challenge 4, I found my own data set for housing prices in California, and created my own visualizations to attempt to show a correlation between avocado sales and housing prices in California. After a failed first attempt, I was able to revise my challenge and used a better approach to display total avocados purchased per region against region and housing price. In Challenge 8, I completed the hardest option, and used an argument of the glue collapse function that wasn't used in class to properly space the lyrics to the Twelve Days of Christmas. Finally in Challenge 9, I added a series of modifications to the data table function to make the table more visually appealing. Additionally, I found a function that created search boxes that allows a user to filter data simultaneously for each column. My group in the class eventually shrunk down to just Austin and I, but we were still able to complete practice activities together and remain in touch outside of class. Because we were a two person team, we acted as duel facilitators during our practice activities and asked questions to Dr. T in tandem. I was present to every class session with the preview activity completed prior to the first class each week. Lastly, I believe I've given peer reviews that give constructive criticism and enable my peers to make positive changes to their code. For example, when reviewing a peers' Lab 7, I offered to help him with any questions he might have because I knew he'd been struggling with a few problems, and gave him some tips to help consistently format his code and use the summarize function correctly. When reviewing another peers' code in Lab 3, I couldn't find any glaring problems with the code, so I only wrote about the parts of the code I loved. I even let them know I learned something new by reviewing their code.
