---
title: "Stat 331 Portfolio"
author: "Scott Brydon"
format: 
  html: 
    theme:
      dark: darkly
    code-fold: true
    code-block-bg: '#063970'
editor: visual
---

# Table of Contents

## Final Grade Reflection

## Essay Responses

Growth as a data scientist

The power of efficiency

Lightning round

## Week 6 Reflection

Now that we've passed the halfway point for the class, I feel that I've become exponentially more prepared to work in a data scientist or analyst position post-college. Therefore, I feel like my goals are being accomplished. I feel more prepared primarily because of our recent use of complicated data visualizations and summarization throughout these last few weeks. For example, I feel that I've gained proficiency in all the Data Visualization & Summarization learning targets except for DVS-3. In Challenge 3, I was able to show my ability to summarize variables across multiple groups when finding the highest difference in music genre familiarity across white and non-white groups, which satisfies DVS-5. In Lab 4 Question 7, I was able to successfully replicate the graph showing the proportion of avocados by size sold in each California region. This graph required a visualization of factor, numerical, and categorical variables to provide enough visual information. Secondly, the x-axis labels were difficult to read, which required the use of a dodge to stagger the labels. Lastly, the proportion of avocados sold by size had to be calculated using mutate, mean, and simple division. After completing the question and submitting revisions, I was able to show proficiency in DVS-1, DVS-2, and DVS-4. In my Week 3 Reflection, I wasn't familiar with the Working with Data learning target WD-5, and the Reproducibility learning target R-3. I feel confident in my proficiency for WD-5, which I practiced heavily throughout Week 4 with the use of semi join and anti-join. I even showed use of it in Lab 4 Question 7. As for R-3, the summarize and select functions used in Challenge 3 Letter B show programs that are resistant to change in inputs due to the use of column names rather than indexing by numerical position. I had a problem with indexing by numerical position when writing my Week 3 Reflection, so I'm happy I'm able to show proficiency in that learning target now.

I've demonstrated a commitment to continued learning by completing every Challenge problem and making corrections to each Challenge I've received feedback for. Throughout my solving of these problems, I used stack overflow frequently, which has helped my Program Efficiency. My proficiency in learning target PE-4 has drastically increased because I'm able to see the most efficient ways other people have been able to utilize different functions in the tidy verse. I've grown as a team member and a leader as the labs have gotten continually harder because our group has had to communicate more than in Weeks 1-3 to be able to complete the labs and challenge assignments. I've started to utilize discord more and have even posted a few questions which I believe other students benefited from as well. By doing so, I feel I'm helping turn discord into the helpful tool it was intended to be at the start of this quarter. Unfortunately, I haven't been good about answering other people's discord questions so far, which is something I need to start actively doing. I can't expect an answer for every question I have if I'm not helping provide other students with answers as well.

I believe my current grade is an A-. I've submitted full attempts/solutions for every assignment, completed almost all assignments on time, and have demonstrated proficiency in the vast majority of learning targets. I've revised my code for every lab or challenge I've received feedback on and have shown an increase in quality of assignments as I continue to make revisions. I've been a helpful group member in and out of class, and I ask questions when needed in class or on discord but have been sub par about answering other student's questions on discord. Lastly, I believe I've given peer reviews that give constructive criticism and enable my peers to make positive changes to their code. But I also believe I could've given better feedback in my earlier peer reviews now that I'm not as naive to R.

## Supporting Artifacts

1.  **WD-1 Importing Data**
    1.  (Challenge 3 Loading California and Avocado Data, Preview Activity 2 Step 2)
2.  **WD-2 Selecting Necessary Columns**
    1.  (Challenge 3 Letter B)
3.  **WD-3 Filtering Rows by Variety of Data Types**
    1.  (Lab 3 Study Subjects, Practice Activity 5 Question 1, Lab 3 Familiar Words)
4.  **WD-4 Modifying Existing Variables and Creating New Variables**
    1.  (Lab 3 Question 4/6, Lab 4 Question 6, Practice Activity 5 Adjusting Time Zone)
5.  **WD-5 Mutating Joins**
    1.  (Preview Activity 4 A/B)
6.  **WD-6 Filtering Joins**
    1.  (Lab 4 Question 7)
7.  **WD-7 Pivoting Data Frames**
    1.  (Lab 4 Question 6/7)
8.  **R-1 Professional Looking Analysis**
    1.  (Lab 3)
9.  **R-2 Well Documented and Tidy Code**
    1.  (Lab 3 Familiar Words, Lab 4 Question 5)
10. **R-3 Robust Programs Resistant to Changes in Inputs**
    1.  (Lab 7 Part 2 Task1/2/3, Lab 4 Question 4, Challenge 3 Letter B)
11. **DVS-1 Visualizations for a Variety of Data Types**
    1.  (Lab 4 Question 7, Lab 5 Time Series Plots #2, Lab 7 Task 4)
12. **DVS-2 Plot Modifications for Clear Visualizations**
    1.  (Lab 4 Question 7, Challenge 7 Part 3) Maybe More...
13. **DVS-3 Creativity in Visualizations**
    1.  (Lab 5 Time Series Plots Question 2, Challenge 7 Part 3, Challenge 4 Letter C)
14. **DVS-4 Calculating Numerical Summaries**
    1.  (Lab 3 Familiar Words)
15. **DVS-5 Summaries of Variables Across Groups**
    1.  (Challenge 3 Letter B)
16. **DVS-6 Tables with Clear Summaries**
    1.  (Challenge 9 Part 2 Question 1 and 2, Lab 4 Exercises 3/4)
17. **DVS-7 Creativity in Tables**
    1.  (Challenge 9 Part 2 Question 1 and 2)
18. **PE-1 Concise Code**
    1.  (Lab 4 Reshaping Question 6, Challenge 3 Letter B, Lab 5 Time Series Plots #2)
19. **PE-2 Functions to Reduce Repetition**
    1.  (Lab 8 Phrase Function/Sing Day Function)
20. **PE-3 Iteration to Reduce Repetition**
    1.  (Lab 8 Step Four)
21. **PE-4 Modern Tools for Analysis**
    1.  ()
22. **DSM-1 Simulating Data for a Variety of Probability Models**
    1.  (Practice Activity 9 Instruments: Catching a Con)
23. **DSM-2 Linear Regression and Extraction of Summary Measures**
    1.  (Lab 9 Modelling the Number of Allison's Question 4 and 5)

### Demonstration of Learning Targets

### Demonstration of Continued Learning

#### Revising My Thinking

#### Extending My Thinking

### Growth as a Team Member
