---
title: "My Growth as a Data Scientist"
format: 
  html:
    self-contained: true
editor: visual
---

I've taken statistics and economics classes at Cal Poly that involved the use of different coding languages to sort data and retrieve relevant numerical summaries, but STAT 331 exposed me to the complexity of data science concepts I'd only scraped the surface of in those courses. First and foremost, the amount of data wrangling needed to complete assignments exposed me to a necessary and overlooked area in data science: data wrangling. There's different names for data wrangling, like data cleaning, but I'm referring to the general process of prepping large amounts of data so it can be leveraged to find valuable insights. I'd previously been handed data sets that had already been arranged and cleaned, so no prior work was required to run analysis on them. Fortunately, the majority of my code in labs and challenges focused solely on cleaning and arranging data, so I feel confident in my ability to handle the dreadful looking data sets I may see in my future career. A great example of my growth in this area lies in Lab 4 Question 6, where I was interested in graphing the differences in Conventional vs Organic avocado prices in four California regions. The data set I was given has large amounts of raw data on avocado sales from all over the United States, and had unorganized avocado price data for all those entries. I first had to sort the data to include only sales from the four specific regions, then create groupings of the data by region and type as those were primary focuses of the future graph. After summarizing the avocado prices by type to get two averages, I had to pivot the data table into a wider format. By doing so, I gave myself the ability to subtract the newly created columns to find the numerical summaries that made up the y-axis. Plotting those values is simple, but wrangling the data to allow for those values to be plotted was a process I was very unfamiliar with. Lastly, the improvement in my data visualization skills is what I'm most proud of in STAT 331. I've always been able to make simple bar, scatter, line, and box plots, however, the data I was previously visualizing was, like my past graphs, simple. But, the field of data science delves into exceptionally complex areas, and the insights gained by data scientists in those areas cannot be easily explained using simple graphs. Explaining complex insights to peers, coworkers, or whoever else may be of interest is most easily done, in my opinion, with verbal explanation accompanied by superb graphs. I've always felt confident in my verbal explanation, and now feel my ability to graph multiple variable types, format graphs to highlight their importance, and subset them to show insights for different categorical variables has made me a viable data scientist. A great example of this improvement was in Challenge 7 Part 3, where I was asked to make a visualization that showed the health of certain fish species on the Blackfoot River in Montana over a 17 year period. One graph would could never show the data clearly because there were four fish species being monitored, and there had been two separate trips taken to monitor those fish each year. By using a facet to create 8 individual graphs per species and per trip, and properly labeling each axis for the reader, I was able to make a visualization that insights could be drawn from easily. I feel drastically more prepared to enter the field of data science now that I've strengthened my skills in Data wrangling and visualization.
