---
title: "Practive Activity 4"
author: "Scott Brydon"
format: html
editor: visual
execute:
  echo: false
---

#### Data Import

```{r}
#Reading in Excel with Skips etc.
library(here)
library(readxl) 
library(tidyverse)

military <- read_xlsx(here("Week 4", "Practice Activity", "gov_spending_per_capita.xlsx"), 
                      sheet = "Share of Govt. spending", 
                      skip = 7, 
                      n_max = 190)
```

#### Data Cleaning

```{r}
#2.Converting missing values to NAs
military_clean <- military |> 
  mutate(across(everything(), na_if, y = ". ."),
         across(everything(), na_if, y = "xxx")
         )
```

```{r}
#3. Coverting year columns to numerics
military_clean <- military_clean |> 
  mutate(across("1988":"2019", as.numeric))
```

```{r}
#Reading in region data
cont_region <- read_xlsx(here("Week 4", "Practice Activity", "gov_spending_per_capita.xlsx"), 
                      sheet = "Regional totals", 
                      skip = 14) |> 
  filter(Region != "World total (including Iraq)", 
         Region != "World total (excluding Iraq)")
```

```{r}
#4. anti_join to filter unwanted country values
military_unwanted <- cont_region |> 
  anti_join(military_clean, by = c("Region" = "Country"))
```

#### Data Organization

```{r}
#4. Putting years into one column
military_long <- military_clean |> 
  pivot_longer("1988":"2019",
               names_to = "Year",
               values_to = "Spending")
```

```{r}
#5. Boxplots of no long data
military_long |> 
  ggplot(mapping = aes(y = Country, x = Spending)) +
  geom_boxplot()
```
